# Generated by Django 2.0 on 2017-12-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_currency', models.CharField(max_length=50)),
                ('base_currency', models.CharField(max_length=50)),
                ('market_currency_long', models.CharField(max_length=100)),
                ('base_currency_long', models.CharField(max_length=100)),
                ('min_trade_size', models.IntegerField()),
                ('market_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
