# Generated by Django 2.0 on 2017-12-17 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary_writer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSummary',
            fields=[
                ('market', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='summary_writer.Market')),
                ('high', models.DecimalField(decimal_places=10, max_digits=19)),
                ('low', models.DecimalField(decimal_places=10, max_digits=19)),
                ('last', models.DecimalField(decimal_places=10, max_digits=19)),
                ('volume', models.DecimalField(decimal_places=10, max_digits=19)),
                ('base_volume', models.DecimalField(decimal_places=10, max_digits=19)),
                ('updated_on', models.DateTimeField()),
                ('bid', models.DecimalField(decimal_places=10, max_digits=19)),
                ('ask', models.DecimalField(decimal_places=10, max_digits=19)),
                ('prev_day', models.DecimalField(decimal_places=10, max_digits=19)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
