# Generated by Django 2.0 on 2017-12-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_writer', '0002_marketsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketsummary',
            name='ask',
            field=models.DecimalField(decimal_places=8, max_digits=50),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='base_volume',
            field=models.DecimalField(decimal_places=8, max_digits=50),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='bid',
            field=models.DecimalField(decimal_places=8, max_digits=50),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='high',
            field=models.DecimalField(decimal_places=8, max_digits=50),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='last',
            field=models.DecimalField(decimal_places=8, max_digits=50),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='low',
            field=models.DecimalField(decimal_places=8, max_digits=50),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='prev_day',
            field=models.DecimalField(decimal_places=8, max_digits=50),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='volume',
            field=models.DecimalField(decimal_places=8, max_digits=50),
        ),
    ]
